kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: openwrtorg/imagebuilder
    volumes:
      - name: cache
        path: /home/build/openwrt/bin
    commands:
      - cd /home/build/openwrt && make image

  - name: publish
    image: plugins/github-release
    volumes:
      - name: cache
        path: /bin
    settings:
      api_key: 
        from_secret: access_token
      files:
        - /bin/*
    when:
      event: tag
